version = 5.6.0
archive_dir = /etc/letsencrypt/archive/swimmingup.hopto.org
cert = /etc/letsencrypt/live/swimmingup.hopto.org/cert.pem
privkey = /etc/letsencrypt/live/swimmingup.hopto.org/privkey.pem
chain = /etc/letsencrypt/live/swimmingup.hopto.org/chain.pem
fullchain = /etc/letsencrypt/live/swimmingup.hopto.org/fullchain.pem
[renewalparams]
account = 8692e190a037e7a890f5991b0ad8e4b1
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
