server {
    listen 80;
    server_name swimmingup;

    client_max_body_size 64m;
    resolver 127.0.0.11 valid=10s ipv6=off;

    set $backend_upstream backend:8000;
    set $frontend_upstream frontend:5173;
    set $wordpress_upstream wordpress:80;
    set $phpmyadmin_upstream phpmyadmin:81;

    location /api/ {
        proxy_pass http://$backend_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location = /blog {
        return 301 /blog/;
    }
    location /blog/ {
        rewrite ^/blog(/.*)$ $1 break;
        
        proxy_pass http://$wordpress_upstream; 
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Prefix /blog;
    }

    location /phpmyadmin/ {
        proxy_pass http://$phpmyadmin_upstream/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Prefix /phpmyadmin;
    }

    location / {
        proxy_pass http://$frontend_upstream;
        proxy_http_version 1.1;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
